# Generated by Django 4.0.4 on 2022-05-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
