# Generated by Django 4.0.4 on 2022-06-03 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_homework_chore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='ownerId',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='ownerId',
            new_name='owner_id',
        ),
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 6, 3)),
        ),
        migrations.AlterField(
            model_name='chore',
            name='size',
            field=models.CharField(choices=[('SML', 'Small'), ('MDM', 'Medium'), ('LRG', 'Large')], max_length=3),
        ),
        migrations.AlterField(
            model_name='chore',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('DON', 'Done')], max_length=255),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('DON', 'Done')], max_length=255),
        ),
    ]
