# Generated by Django 4.0.4 on 2022-06-06 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_ownerid_chore_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 6, 6)),
        ),
    ]
