# Generated by Django 4.0.4 on 2022-06-10 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_chore_type_homework_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6),
        ),
        migrations.AlterField(
            model_name='chore',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done')], max_length=6),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 6, 10)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done')], max_length=6),
        ),
    ]
